### PR TITLE
LBS app support

### PR DESCRIPTION
**Pull request by justFredster**

### CODE REVIEW

**Comment by LarsCJensen** [comment]
Just a quick thought - if the app needs a BAS file, a table etc then the user need to know that before hand. How should we handle that? My guess is that it will problably cause some issues. For instance, I wanted to add infotiles to my package but realized that it needs a BAS file as well as localizations. I'm therefore beginning to wonder if the possibility to add LBS apps really is such a good idea after all.

**Comment by LarsCJensen** [comment]
When I opened an existing package with an app inside I got an error:

image

[lip-Test of Addon.zip](https://github.com/Lundalogik/addon-lip-package-builder/files/2572479/lip-Test.of.Addon.zip)

**Comment by justFredster** [comment]
> When I opened an existing package with an app inside I got an error:
> 
> image
> 
> [lip-Test of Addon.zip](https://github.com/Lundalogik/addon-lip-package-builder/files/2572479/lip-Test.of.Addon.zip)

I got the same error while testing for the linked package.

**Comment by justFredster** [comment]
Issue described above solved now. Please test @LarsCJensen 
Also added setting mousepointer to loading when opening existing package and an alert showing that the package loaded successfully to give feedback that it was done.

**Pull request merged**
